### ISSUE TITLE
running with the openshift instructions causes an error

### ISSUE THREAD

**Issue by elmiko** [elmiko/jgrafzahl#1]
when i try to deploy this in openshift, i see the following error in the jgrafzahl pod

```
version 1
Didn't find cluster cluster-p17cas, creating...
Waiting for spark master http://cluster-p17cas-ui:8080 to be available ...
Waiting for spark master http://cluster-p17cas-ui:8080 to be available ...
Waiting for spark master http://cluster-p17cas-ui:8080 to be available ...
Waiting for spark workers (0/1 alive) ...
All spark workers alive
spark-submit --class io.radanalytics.jgrafzahl.App --master spark://cluster-p17cas:7077 --packages org.apache.spark:spark-sql-kafka-0-10_2.11:2.1.0,com.sparkjava:spark-core:2.5.5 /opt/app-root/src/jgrafzahl-1.0-SNAPSHOT.jar apache-kafka:9092 word-fountain
Ivy Default Cache set to: /.ivy2/cache
The jars for the packages stored in: /.ivy2/jars
:: loading settings :: url = jar:file:/opt/spark-2.1.0-bin-hadoop2.7/jars/ivy-2.4.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
org.apache.spark#spark-sql-kafka-0-10_2.11 added as a dependency
com.sparkjava#spark-core added as a dependency
:: resolving dependencies :: org.apache.spark#spark-submit-parent;1.0
	confs: [default]
Exception in thread "main" java.io.FileNotFoundException: /.ivy2/cache/resolved-org.apache.spark-spark-submit-parent-1.0.xml (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at org.apache.ivy.plugins.parser.xml.XmlModuleDescriptorWriter.write(XmlModuleDescriptorWriter.java:70)
	at org.apache.ivy.plugins.parser.xml.XmlModuleDescriptorWriter.write(XmlModuleDescriptorWriter.java:62)
	at org.apache.ivy.core.module.descriptor.DefaultModuleDescriptor.toIvyFile(DefaultModuleDescriptor.java:563)
	at org.apache.ivy.core.cache.DefaultResolutionCacheManager.saveResolvedModuleDescriptor(DefaultResolutionCacheManager.java:176)
	at org.apache.ivy.core.resolve.ResolveEngine.resolve(ResolveEngine.java:245)
	at org.apache.ivy.Ivy.resolve(Ivy.java:523)
	at org.apache.spark.deploy.SparkSubmitUtils$.resolveMavenCoordinates(SparkSubmit.scala:1076)
	at org.apache.spark.deploy.SparkSubmit$.prepareSubmitEnvironment(SparkSubmit.scala:296)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:160)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:126)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Deleting cluster
```

**Comment by pdmack** [comment]
As suspected, this is a permission problem where the user created for the submit image doesn't have write permission to what is the default location for the ivy local cache (/root/.ivy2/cache). The ivy local cache population is triggered by the use of the additional `--packages` option. Spark has a poorly named config property for overriding this location (spark.jars.ivy). A workaround is just to use /tmp/.ivy2.

`oc new-app --template=oshinko-java-spark-build-dc -p APPLICATION_NAME=jgrafzahl -p GIT_URI=https://github.com/elmiko/jgrafzahl -p APP_MAIN_CLASS=io.radanalytics.jgrafzahl.App            -p APP_ARGS='apache-kafka:9092 word-fountain' -p SPARK_OPTIONS='--packages org.apache.spark:spark-sql-kafka-0-10_2.11:2.1.0,com.sparkjava:spark-core:2.5.5 --conf spark.jars.ivy=/tmp/.ivy2'`

Using this launches the submit (although I didn't have a Kafka server set up).
 
There is an upstream doc bug for this: https://issues.apache.org/jira/browse/SPARK-19630

The property ivy.default.ivy.user.dir might also have the same effect but YMMV.

**Comment by elmiko** [comment]
very cool, many thanks Pete!

**Comment by elmiko** [comment]
updated the readme in this commit https://github.com/elmiko/jgrafzahl/commit/ba0c7df03e842580c8da3c415a4112eaa02a988f
